language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  matrix:
    - MONGODB=2.6.12
    - MONGODB=3.0.12
    - MONGODB=3.2.10
    - MONGODB=3.4.0-rc0

matrix:
  fast_finish: true

install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - export PATH=${PWD}/mongodb-linux-x86_64-${MONGODB}/bin:${PATH}
  - mongod --version
  - pip install Pillow
  - python setup.py install

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork

script:
  - python setup.py test

after_script:
  - pkill mongod